// src/types/tabs.ts

// Unified tab identifier type used across the application.
// Keep this list in sync with the activeTab state in App.tsx.
export type TabId =
  | 'Home'
  | 'SalesOverview'
  | 'Invoices'
  | 'OnlinePayments'
  | 'Quotes'
  | 'Products'
  | 'Customers'
  | 'SalesSettings'
  | 'PurchasesOverview'
  | 'Bills'
  | 'PurchaseOrders'
  | 'Cheque'
  | 'Expenses'
  | 'Suppliers'
  | 'PurchasesSettings'
  | 'FixedAssets'
  | 'Payroll'
  | 'AllReports'
  | 'AccountTransactions'
  | 'BalanceSheet'
  | 'ProfitAndLoss'
  | 'ReportingSettings'
  | 'reconcile'
  | 'ChartOfAccounts'
  | 'AccountingSettings'
  | 'Contacts'
  | 'ContactsSettings'
  | 'TaxRates'
  | 'CreateInvoice'
  | 'CreateQuote'
  | 'EditInvoice'
  | 'EditQuote'
  | 'CreateBill'
  | 'EditBill'
  | 'CreatePurchaseOrder'
  | 'EditPurchaseOrder'
  | 'CreateTransferMoney'
  | 'CreateSpendMoney'
  | 'CreateReceiveMoney'
  | 'CreateManualJournal'
  | 'Projects';
